[2022-08-01 22:37:28,137]^;INFO^;224^;configuration.py^;get_training_pipeline_config()^;Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact')
[2022-08-01 22:37:28,267]^;INFO^;224^;_internal.py^;_log()^; * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
[2022-08-01 22:39:48,675]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [01/Aug/2022 22:39:48] "GET / HTTP/1.1" 200 -
[2022-08-01 22:39:58,534]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [01/Aug/2022 22:39:58] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2022-08-01 22:40:17,206]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [01/Aug/2022 22:40:17] "GET / HTTP/1.1" 200 -
[2022-08-01 22:40:20,560]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [01/Aug/2022 22:40:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2022-08-01 22:40:42,543]^;INFO^;193^;app.py^;render_log_dir()^;req_path: logs
[2022-08-01 22:40:42,641]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [01/Aug/2022 22:40:42] "GET /logs HTTP/1.1" 200 -
[2022-08-01 22:40:54,322]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [01/Aug/2022 22:40:54] "GET /artifact HTTP/1.1" 200 -
[2022-08-01 22:40:56,143]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [01/Aug/2022 22:40:56] "GET /saved_models HTTP/1.1" 200 -
[2022-08-01 22:40:58,019]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [01/Aug/2022 22:40:58] "GET /predict HTTP/1.1" 200 -
[2022-08-01 22:41:04,894]^;INFO^;224^;configuration.py^;get_training_pipeline_config()^;Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact')
[2022-08-01 22:41:04,895]^;ERROR^;1456^;app.py^;log_exception()^;Exception on /train [GET]
Traceback (most recent call last):
  File "C:\Users\somit\Downloads\project_ineuron\practise_project_1\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\somit\Downloads\project_ineuron\practise_project_1\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\somit\Downloads\project_ineuron\practise_project_1\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\somit\Downloads\project_ineuron\practise_project_1\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 91, in train
    if not Pipeline.experiment.running_status:
AttributeError: type object 'Pipeline' has no attribute 'experiment'
[2022-08-01 22:41:04,902]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [01/Aug/2022 22:41:04] "[35m[1mGET /train HTTP/1.1[0m" 500 -
