[2022-07-14 06:23:17,258]^;INFO^;114^;configuration.py^;get_training_pipeline_config()^;Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact')
[2022-07-14 06:23:17,259]^;INFO^;65^;configuration.py^;get_data_ingestion_config()^;Data Ingestion config: DataIngestionConfig(dataset_download_url='https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz', tgz_download_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact\\data_ingestion\\2022-07-14-06-23-11\\tgz_data', raw_data_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact\\data_ingestion\\2022-07-14-06-23-11\\raw_data', ingested_train_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact\\data_ingestion\\2022-07-14-06-23-11\\ingested_data\\train', ingested_test_dir='C:\\Users\\somit\\Downloads\\project_ineuron\\practise_project_1\\housing\\artifact\\data_ingestion\\2022-07-14-06-23-11\\ingested_data\\test')
[2022-07-14 06:23:17,260]^;INFO^;16^;data_ingestion.py^;__init__()^;>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log started.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
[2022-07-14 06:23:17,262]^;INFO^;37^;data_ingestion.py^;download_housing_data()^;Downloading file from :[https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz] into :[C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\artifact\data_ingestion\2022-07-14-06-23-11\tgz_data\housing.tgz]
[2022-07-14 06:23:17,829]^;ERROR^;25^;demo.py^;main()^;
        Error occured in script: 
        [ C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\pipeline\pipeline.py ] at 
        try block line number: [52] and exception block line number: [56] 
        error message: [
        Error occured in script: 
        [ C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\pipeline\pipeline.py ] at 
        try block line number: [28] and exception block line number: [31] 
        error message: [
        Error occured in script: 
        [ C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\component\data_ingestion.py ] at 
        try block line number: [120] and exception block line number: [124] 
        error message: [
        Error occured in script: 
        [ C:\Users\somit\Downloads\project_ineuron\practise_project_1\housing\component\data_ingestion.py ] at 
        try block line number: [38] and exception block line number: [43] 
        error message: [<urlopen error [Errno 11001] getaddrinfo failed>]
        ]
        ]
        ]
        
[2022-07-14 06:23:17,855]^;INFO^;129^;data_ingestion.py^;__del__()^;>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log completed.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 


